STEAM 1099 FHIR endpoint front-end
mcode/mcode-coverage-checker pull request #42
Opened 2023-04-12 01:03 UTC by AldenB0

# Description
Issue: STEAM 1099

Front-end for the FHIR endpoint

## Demo/Screenshots
![image](https://user-images.githubusercontent.com/87581687/231319744-5c2c62d7-0248-4462-a514-106ac9420b47.png)

## Important Changes
`FHIRendpoint.js`
- Created input field, connect button, and advanced options dropdown.

_General changes_

`FileUploadPage.js`
- Added the Endpoint to the page.

`AdvancedOptions.js`
- Created a placehoder for advanced options if we are planning on eventually pursuing that direction.

# Checklists

**Submitter:**
- [ ] This PR describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] This PR includes the correct JIRA issue reference.
- [ ] Code diff has been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)

@ACCT1 :
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] You have tried to break the code
- [ ] Tested all recommendations listed in the "Testing Recommendations" section. The application behaves as expected with this PR.

2023-04-12 17:41 UTC, dmendelowitz requested changes
A couple of minor changes, but overall this looks great!

2023-04-12 17:41 UTC, dmendelowitz commented on src/components/FHIRendpoint.js
> +      <div
I think we should move all the advanced options related stuff in this file into the actual advanced options component file

2023-04-12 17:41 UTC, dmendelowitz commented on src/components/FHIRendpoint.js
> +            placeholder="https://api.examplePath.org/RTTD/open"
Let's make the placeholder something more generic like `http://example.org/` or whatever, we don't want to make anyone think they need any specific queries with the slash extensions

2023-04-13 12:46 UTC, dmendelowitz approved these changes

2023-04-13 12:47 UTC, merged

2023-04-13 19:44 UTC, Dtphelan1 commented
This is looking really good guys, miss you both but glad that I still get to see the updates as they come in. 😄